<div class="row">
    <div class="col-lg-3 mb-3 mb-lg-0">
        <div class="card p-1">
            <div class="card-body text-center">
                <div class="mb-3">
                    <img class="rounded-circle" 
                         src="<?= $this->basePath('images' . DS . 'avatars' . DS . $this->escapeHtml($this->account->getPicture())); ?>" 
                         alt="<?= $this->escapeHtml($this->account->getUsername()); ?>'s image"
                         height="50%"
                         width="50%">
                </div>

                <div class="mb-3">
                    <h1 class="h6 font-weight-medium mb-0">
                        <?= $this->escapeHtml($this->account->getUsername()); ?>
                    </h1>
                    <small class="d-block text-muted">
                        <?= $this->escapeHtml($this->account->getGender()); ?>
                    </small>
                </div>
            </div>
        </div>
    </div>
</div>
