<?php

$title = $this->translate('Login');
$this->headMeta()->appendName('keywords', 'Login, Sign In, Authenticate');
$this->headMeta()->appendName('description', 'Login to my account');
$this->headTitle($this->escapeHtml($title));

$form = $this->form;
$form->setAttribute('action', $this->url('login'));
$form->prepare();
?>

<div class="container">
    <div class="row justify-content-center">

        <div class="col-md-4 shadow-sm">

            <h1 class="text-center mb-3">
                <span class="text-muted">
                    <?= $this->translate('Member Login'); ?>
                </span>
            </h1>

            <?= $this->form()->openTag($form); ?>

            <p class="text-muted mb-2">
                <?= sprintf(
                    $this->translate('Don\'t have an account yet? %sJoin here%s.'),
                    '<a href="'.$this->url('signup').'">', '</a>'
                ); ?>
            </p>

            <div class="mb-3">
                <?= $this->formLabel($form->get('email')); ?>
                <div class="input-group">
                    <?= $this->formEmail($form->get('email')); ?>
                </div>
                <div class="text-danger">
                    <?= $this->formElementErrors($form->get('email')); ?>
                </div>
            </div>

            <div class="mb-3">
                <?= $this->formLabel($form->get('password')); ?>
                <span class="float-end">
                    <?= sprintf(
                        $this->translate('%sForgot Password?%s'),
                        '<a href="'.$this->url('forgot').'">', '</a>'
                    ); ?>
                </span>
                <div class="input-group">
                    <?= $this->formPassword($form->get('password')); ?>
                </div>
                <div class="text-danger">
                    <?= $this->formElementErrors($form->get('password')); ?>
                </div>
            </div>

            <div class="mb-3 form-check">
                <?= $this->formCheckbox($form->get('recall')); ?>
                <?= $this->formLabel($form->get('recall')); ?>
            </div>

            <div class="mb-3">
                <?= $this->formHidden($form->get('returnUrl')); ?>
                <?= $this->formHidden($form->get('csrf')); ?>
                <div class="text-danger">
                    <?= $this->formElementErrors($form->get('csrf')); ?>
                </div>
                <?= $this->formSubmit($form->get('account_login')); ?>
            </div>

            <?= $this->form()->closeTag(); ?>
        </div>
    </div>
</div>
