<?php

$title = $this->translate('Update Email');
$this->headMeta()->appendName('keywords', 'Edit, Update, Change, Email Address');
$this->headMeta()->appendName('description', 'Change my email address');
$this->headTitle($this->escapeHtml($title));

$form = $this->form;
$form->setAttribute('action', $this->url('settings', ['action' => 'email']));
$form->prepare();
?>

<div class="container">

    <div class="row mb-3">
        <div class="nav-scroller bg-white shadow-sm">
            <nav class="nav nav-underline">
                <a class="nav-link active" href="<?= $this->url('settings', ['action' => 'index']); ?>">Settings Dashboard</a>
                <a class="nav-link" href="<?= $this->url('settings', ['action' => 'email']); ?>">
                    <?= $this->translate('Edit Email Address'); ?>
                </a>
                <a class="nav-link" href="<?= $this->url('settings', ['action' => 'password']); ?>">
                    <?= $this->translate('Edit Password'); ?>
                </a>
                <a class="nav-link" href="<?= $this->url('settings', ['action' => 'upload']); ?>">
                    <?= $this->translate('Upload Profile Picture'); ?>
                </a>
                <a class="nav-link" href="<?= $this->url('settings', ['action' => 'username']); ?>">
                    <?= $this->translate('Edit Username'); ?>
                </a>
                <a class="nav-link" href="<?= $this->url('settings', ['action' => 'delete']); ?>">
                    <?= $this->translate('Delete Account'); ?>
                </a>
            </nav>
        </div>
    </div>

    <div class="row justify-content-center">

        <div class="col-md-6 shadow-sm">

            <h2 class="text-center mb-3 pt-2">
                <span class="text-muted">
                    <?= $this->translate('Change My Email Address'); ?>
                </span>
            </h2>

            <?= $this->form()->openTag($form); ?>

            <div class="mb-3">
                <?= $this->formLabel($form->get('current_email')); ?>
                <div class="input-group">
                    <?= $this->formEmail($form->get('current_email')->setValue($this->authHelper()->getEmail())); ?>
                </div>
                <div class="text-danger">
                    <?= $this->formElementErrors($form->get('current_email')); ?>
                </div>
            </div>

            <div class="mb-3">
                <?= $this->formLabel($form->get('new_email')); ?>
                <div class="input-group">
                    <?= $this->formEmail($form->get('new_email')); ?>
                </div>
                <div class="text-danger">
                    <?= $this->formElementErrors($form->get('new_email')); ?>
                </div>
            </div>

            <div class="mb-3">
                <?= $this->formLabel($form->get('confirm_new_email')); ?>
                <div class="input-group">
                    <?= $this->formEmail($form->get('confirm_new_email')); ?>
                </div>
                <div class="text-danger">
                    <?= $this->formElementErrors($form->get('confirm_new_email')); ?>
                </div>
            </div>

            <div class="mb-3">
                <?= $this->formHidden($form->get('csrf')); ?>
                <div class="text-danger">
                    <?= $this->formElementErrors($form->get('csrf')); ?>
                </div>
                <?= $this->formSubmit($form->get('update_email')); ?>
            </div>

            <?= $this->form()->closeTag(); ?>
        </div>
    </div>
</div>
