<?php

$title = $this->translate('Upload Picture');
$this->headMeta()->appendName('keywords', 'Upload, Profile, Avatar, Picture');
$this->headMeta()->appendName('description', 'Upload profile picture');
$this->headTitle($this->escapeHtml($title));

$form = $this->form;
$form->setAttribute('action', $this->url('settings', ['action' => 'upload']));
$form->prepare();
?>

<div class="container">

    <div class="row mb-3">
        <div class="nav-scroller bg-white shadow-sm">
            <nav class="nav nav-underline">
                <a class="nav-link active" href="<?= $this->url('settings', ['action' => 'index']); ?>">Settings Dashboard</a>
                <a class="nav-link" href="<?= $this->url('settings', ['action' => 'email']); ?>">
                    <?= $this->translate('Edit Email Address'); ?>
                </a>
                <a class="nav-link" href="<?= $this->url('settings', ['action' => 'password']); ?>">
                    <?= $this->translate('Edit Password'); ?>
                </a>
                <a class="nav-link" href="<?= $this->url('settings', ['action' => 'upload']); ?>">
                    <?= $this->translate('Upload Profile Picture'); ?>
                </a>
                <a class="nav-link" href="<?= $this->url('settings', ['action' => 'username']); ?>">
                    <?= $this->translate('Edit Username'); ?>
                </a>
                <a class="nav-link" href="<?= $this->url('settings', ['action' => 'delete']); ?>">
                    <?= $this->translate('Delete Account'); ?>
                </a>
            </nav>
        </div>
    </div>

    <div class="row justify-content-center">

        <div class="col-md-6 shadow-sm">

            <h2 class="text-center mb-3">
                <span class="text-muted">
                    <?= $this->translate('Upload Profile Picture'); ?>
                </span>
            </h2>

            <?= $this->form()->openTag($form); ?>

            <span class="text-muted form-text">
                <?= $this->translate(''); ?>
            </span>

            <div class="mb-3">
                <div class="input-group">
                    <div class="custom-file">

                        <?= $this->formFile($form->get('picture')); ?>
                        <?= $this->formLabel($form->get('picture')); ?>
                    </div>
                    <div class="input-group-append">
                        <?= $this->formSubmit($form->get('upload_picture')); ?>
                    </div>
                </div>
                <div class="text-danger">
                    <?= $this->formElementErrors($form->get('picture')); ?>
                </div>
            </div>

            <?= $this->form()->closeTag(); ?>
        </div>
    </div>
</div>

<script>
    $(function() {
        $('#picture').on('change', function () {
            $('label[for="picture"]').text($(this).val().split("\\").splice(-1, 1)[0]);
        });
    });
</script>
