<?php

$title = $this->translate('Manage Accounts');
$this->headMeta()->appendName('keywords', 'Admin, Manage, User, Account');
$this->headMeta()->appendName('description', 'Manager all user account');
$this->headTitle($this->escapeHtml($title));

?>
    <h2>
    <span class="text-secondary">
        <?= $this->translate('Manage Accounts'); ?>
    </span>
        <span class="float-right">
        <a href="<?= $this->url('admin_quiz', ['action' => 'index']); ?>"
           class="text-primary">
            <?= $this->translate('Manage Quizzes'); ?>
            &gt;&gt;
        </a>
    </span>
    </h2>

    <div class="table-responsive">
        <table class="table table-striped table-sm">

            <thead>
            <tr>
                <th>AuthId</th>
                <th>Username</th>
                <th>Email</th>
                <th>Gender</th>
                <th>Role</th>
                <th>Joined On</th>
                <th>Actions</th>
            </tr>
            </thead>

            <tbody>

            <?php foreach ($this->accounts as $account): ?>

                <tr>
                    <td><?= $account->getAuthId(); ?></td>
                    <td><a href="<?= $this->url(
                            'profile',
                            [
                                'id' => $account->getAuthId(),
                                'username' => mb_strtolower(
                                    $account->getUsername())
                            ]); ?>">
                            <?= $account->getUsername(); ?>
                        </a>
                    </td>
                    <td><?= $account->getEmail(); ?></td>
                    <td><?= $account->getGender(); ?></td>
                    <td><?= $account->getRole(); ?></td>
                    <td>
                        <?= $this->dateFormat(
                            new DateTime($account->getCreated()),
                            IntlDateFormatter::MEDIUM, // date
                            IntlDateFormatter::NONE, // time
                            "en_US"
                        ); ?>
                    </td>
                    <td>
                        <a href="<?= $this->url(
                            'admin_user',
                            [
                                'action' => 'edit',
                                'id' => $account->getAuthId()
                            ]); ?>"><?=
                            $this->translate('Edit'); ?></a>
                        <a href="<?= $this->url(
                            'admin_user',
                            [
                                'action' => 'delete',
                                'id' => $account->getAuthId()
                            ]); ?>">
                            <?= $this->translate('Delete'); ?>
                        </a>
                    </td>
                </tr>

            <?php endforeach; ?>
            </tbody>
        </table>
    </div>

<?= $this->paginationControl(
        $this->accounts,
        'sliding',
        'partial/paginator',
        ['route' => 'admin_user']
    );
