<?php

$title = $this->translate('New Quiz');
$this->headMeta()->appendName('keywords', 'Create, Start, New, Quiz');
$this->headMeta()->appendName('description', 'Create a new quiz');
$this->headTitle($this->escapeHtml($title));

$form = $this->form;
$form->setAttribute('action', $this->url('quiz', ['action' => 'create']));
$form->prepare();
?>

<div class="container">
    <div class="row">

        <div class="col-md-6 shadow-sm">

            <h2 class="text-center mb-3 pt-2">
                <span class="text-muted">
                    <?= $this->translate('Start A New Quiz'); ?>
                </span>
            </h2>

            <?= $this->form()->openTag($form); ?>

            <div class="mb-3">
                <?= $this->formLabel($form->get('title')); ?>
                <div class="input-group">
                    <?= $this->formText($form->get('title')); ?>
                </div>
                <div class="text-danger">
                    <?= $this->formElementErrors($form->get('title')); ?>
                </div>
            </div>

            <div class="mb-3">
                <?= $this->formLabel($form->get('category_id')); ?>
                <div class="input-group">
                    <?= $this->formSelect($form->get('category_id')); ?>
                </div>
                <div class="text-danger">
                    <?= $this->formElementErrors($form->get('category_id')); ?>
                </div>
            </div>

            <div class="mb-3">
                <?= $this->formLabel($form->get('timeout')); ?>
                <div class="input-group">
                    <?= $this->formSelect($form->get('timeout')); ?>
                </div>
                <div class="text-danger">
                    <?= $this->formElementErrors($form->get('timeout')); ?>
                </div>
            </div>

            <div class="mb-3">
                <?= $this->formLabel($form->get('question')); ?>
                <div class="input-group">
                    <?= $this->formTextarea($form->get('question')); ?>
                </div>
                <div class="text-danger">
                    <?= $this->formElementErrors($form->get('question')); ?>
                </div>
            </div>

            <div class="mb-3">
                <?= $this->formLabel($form->get('answers[]')); ?>
                <div class="input-group">
                    <?= $this->formText($form->get('answers[]')); ?>
                </div>
                <div class="text-danger">
                    <?= $this->formElementErrors($form->get('answers[]')); ?>
                </div>
            </div>

            <div class="mb-3">
                <div class="input-group">
                    <?= $this->formText($form->get('answers[]')); ?>
                </div>
                <div class="text-danger">
                    <?= $this->formElementErrors($form->get('answers[]')); ?>
                </div>
            </div>

            <div id="wrapper">
                <!-- dynamically created answers field will be placed here -->
            </div>

            <div class="mb-3">
                <?= $this->formButton($form->get('add_more')); ?>
            </div>

            <div class="mb-3 custom-control custom-checkbox">
                <?= $this->formCheckbox($form->get('allow')); ?>
                <?= $this->formLabel($form->get('allow')); ?>
            </div>

            <div class="mb-3">
                <?= $this->formHidden($form->get('auth_id')->setValue($this->authHelper()->getAuthId())); ?>
                <?= $this->formHidden($form->get('csrf')); ?>
                <div class="text-danger">
                    <?= $this->formElementErrors($form->get('csrf')); ?>
                </div>
                <?= $this->formSubmit($form->get('post_quiz')); ?>
            </div>
            <?= $this->form()->closeTag(); ?>
        </div>
    </div>
</div>

<script type="text/javascript">

    $(function() {
        var minimumFields = 2,
            maximumFields = 4,
            inputField = '<div class="mb-3">\n' +
                '<div class="input-group">\n' +
                '<input type="text" name="answers[]" class="form-control" placeholder="Enter a possible answer" title="Provide a possible answer">\n' +
                '<div class="input-group-append delete">\n' +
                '<span class="input-group-text" title="Remove this field">&times;</span>\n'+
                '</div>\n' +
                '</div>\n' +
                '</div>';

        $(document).on('click', '#add_more', function() {
            $('#wrapper').append(inputField);
            minimumFields++;

            if(minimumFields >= maximumFields) {
                $("#add_more").hide();
            }
        });

        $(document).on('click', '.delete', function() {
            $(this).parent().parent().remove();
            minimumFields--;

            if(minimumFields < maximumFields) {
                $("#add_more").show();
            }
        });
    });

</script>